import 'package:terrain/model/parcelle_model.dart';
import 'package:terrain/services/parcelle_service.dart';

void peuplerBaseDeDonnees() async {
  List<Parcelle> parcelles = [
    Parcelle(
      id: '1',
      nomProprietaire: 'Seydou Traoré',
      prenomProprietaire: 'Seydou',
      addresseProprietaire: 'Hamdallaye ACI, Bamako',
      numParcelleOuTitre: 10123,
      numEnregFolios: 3045,
      superficieTerrain: '500m²',
      lieuParcelle: 'Bamako',
      planParcelle: 'Plan A',
      coutMoyenParcelle: '350,000 FCFA/m²',
      latitude: 12.6392,
      longitude: -8.0029,
      verification: true,
      litige: false,
      historiqueTransactions: ['Vente 2015', 'Hypothèque 2020'],
    ),
    Parcelle(
      id: '2',
      nomProprietaire: 'Fatoumata Koné',
      prenomProprietaire: 'Fatoumata',
      addresseProprietaire: 'Quinzambougou, Bamako',
      numParcelleOuTitre: 10234,
      numEnregFolios: 4067,
      superficieTerrain: '300m²',
      lieuParcelle: 'Bamako',
      planParcelle: 'Plan B',
      coutMoyenParcelle: '400,000 FCFA/m²',
      latitude: 12.6392,
      longitude: -8.0123,
      verification: true,
      litige: true, // Litige présent
      historiqueTransactions: ['Vente 2018'],
    ),
    Parcelle(
      id: '3',
      nomProprietaire: 'Moussa Diarra',
      prenomProprietaire: 'Moussa',
      addresseProprietaire: 'Badalabougou, Bamako',
      numParcelleOuTitre: 10345,
      numEnregFolios: 5078,
      superficieTerrain: '600m²',
      lieuParcelle: 'Bamako',
      planParcelle: 'Plan C',
      coutMoyenParcelle: '300,000 FCFA/m²',
      latitude: 12.6354,
      longitude: -8.0029,
      verification: false, // Problème de vérification
      litige: false,
      historiqueTransactions: ['Vente 2017', 'Donation 2019'],
    ),
    Parcelle(
      id: '4',
      nomProprietaire: 'Aminata Coulibaly',
      prenomProprietaire: 'Aminata',
      addresseProprietaire: 'Ségou',
      numParcelleOuTitre: 10456,
      numEnregFolios: 6089,
      superficieTerrain: '700m²',
      lieuParcelle: 'Ségou',
      planParcelle: 'Plan D',
      coutMoyenParcelle: '280,000 FCFA/m²',
      latitude: 13.4317,
      longitude: -6.2157,
      verification: true,
      litige: false,
      historiqueTransactions: ['Vente 2012', 'Hypothèque 2021'],
    ),
    Parcelle(
      id: '5',
      nomProprietaire: 'Ibrahim Diallo',
      prenomProprietaire: 'Ibrahim',
      addresseProprietaire: 'Kayes',
      numParcelleOuTitre: 10567,
      numEnregFolios: 7090,
      superficieTerrain: '450m²',
      lieuParcelle: 'Kayes',
      planParcelle: 'Plan E',
      coutMoyenParcelle: '320,000 FCFA/m²',
      latitude: 14.4469,
      longitude: -11.4394,
      verification: true,
      litige: true,
      historiqueTransactions: ['Vente 2016'],
    ),
    Parcelle(
      id: '6',
      nomProprietaire: 'Oumou Sangaré',
      prenomProprietaire: 'Oumou',
      addresseProprietaire: 'Kati',
      numParcelleOuTitre: 10678,
      numEnregFolios: 8101,
      superficieTerrain: '550m²',
      lieuParcelle: 'Kati',
      planParcelle: 'Plan F',
      coutMoyenParcelle: '270,000 FCFA/m²',
      latitude: 12.7518,
      longitude: -8.0723,
      verification: true,
      litige: false,
      historiqueTransactions: ['Vente 2014', 'Donation 2020'],
    ),
    Parcelle(
      id: '7',
      nomProprietaire: 'Modibo Keita',
      prenomProprietaire: 'Modibo',
      addresseProprietaire: 'Gao',
      numParcelleOuTitre: 10789,
      numEnregFolios: 9112,
      superficieTerrain: '600m²',
      lieuParcelle: 'Gao',
      planParcelle: 'Plan G',
      coutMoyenParcelle: '250,000 FCFA/m²',
      latitude: 16.2669,
      longitude: -0.0447,
      verification: true,
      litige: false,
      historiqueTransactions: ['Vente 2013'],
    ),
    Parcelle(
      id: '8',
      nomProprietaire: 'Adama Sidibé',
      prenomProprietaire: 'Adama',
      addresseProprietaire: 'Sikasso',
      numParcelleOuTitre: 10890,
      numEnregFolios: 10123,
      superficieTerrain: '800m²',
      lieuParcelle: 'Sikasso',
      planParcelle: 'Plan H',
      coutMoyenParcelle: '220,000 FCFA/m²',
      latitude: 11.3173,
      longitude: -5.6666,
      verification: true,
      litige: true, // Litige présent
      historiqueTransactions: ['Vente 2019'],
    ),
    Parcelle(
      id: '9',
      nomProprietaire: 'Kadiatou Touré',
      prenomProprietaire: 'Kadiatou',
      addresseProprietaire: 'Koulikoro',
      numParcelleOuTitre: 10901,
      numEnregFolios: 11234,
      superficieTerrain: '700m²',
      lieuParcelle: 'Koulikoro',
      planParcelle: 'Plan I',
      coutMoyenParcelle: '260,000 FCFA/m²',
      latitude: 12.8614,
      longitude: -7.5522,
      verification: true,
      litige: false,
      historiqueTransactions: ['Vente 2020'],
    ),
    Parcelle(
      id: '10',
      nomProprietaire: 'Boubacar Cissé',
      prenomProprietaire: 'Boubacar',
      addresseProprietaire: 'Mopti',
      numParcelleOuTitre: 11012,
      numEnregFolios: 12345,
      superficieTerrain: '900m²',
      lieuParcelle: 'Mopti',
      planParcelle: 'Plan J',
      coutMoyenParcelle: '230,000 FCFA/m²',
      latitude: 14.4951,
      longitude: -4.1969,
      verification: false, // Problème de vérification
      litige: true,
      historiqueTransactions: ['Vente 2021'],
    ),
  ];

  final parcelleService = ParcelleService();

  for (var parcelle in parcelles) {
    await parcelleService.addParcelle(parcelle);
  }
}
