name: terrain
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.35.0

  


  flutter_map: ^4.0.0  # Ajoutez cette ligne
  latlong2: ^0.8.1 
  pdf: ^3.5.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  # Dépendances Firebase (versions les plus récentes)
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  # Dépendances supplémentaires
  syncfusion_flutter_charts: ^27.1.48
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login.png
