// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfiY9UGzZQdfhQSq2XZS8vsUha9NbN39k',
    appId: '1:957530271324:web:5c51bd3b3ced51ae7d0099',
    messagingSenderId: '957530271324',
    projectId: 'terrain-223',
    authDomain: 'terrain-223.firebaseapp.com',
    storageBucket: 'terrain-223.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgfJZXb5P4sXxfGYN6FUyQWujME9jk0rI',
    appId: '1:957530271324:android:9a7a2db13098870b7d0099',
    messagingSenderId: '957530271324',
    projectId: 'terrain-223',
    storageBucket: 'terrain-223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV8vHZtmDprDwvLm6VJ_rvbZ6KPMuubGs',
    appId: '1:957530271324:ios:5946a7609b4e084b7d0099',
    messagingSenderId: '957530271324',
    projectId: 'terrain-223',
    storageBucket: 'terrain-223.appspot.com',
    iosBundleId: 'com.example.terrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV8vHZtmDprDwvLm6VJ_rvbZ6KPMuubGs',
    appId: '1:957530271324:ios:5946a7609b4e084b7d0099',
    messagingSenderId: '957530271324',
    projectId: 'terrain-223',
    storageBucket: 'terrain-223.appspot.com',
    iosBundleId: 'com.example.terrain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfiY9UGzZQdfhQSq2XZS8vsUha9NbN39k',
    appId: '1:957530271324:web:8267aa4d89bef8927d0099',
    messagingSenderId: '957530271324',
    projectId: 'terrain-223',
    authDomain: 'terrain-223.firebaseapp.com',
    storageBucket: 'terrain-223.appspot.com',
  );
}
